apiVersion: v1
kind: Service
metadata:
  name: {{ include "moltbot-chart.fullname" . }}
  labels:
    {{- include "moltbot-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
    - name: bridge
      port: {{ .Values.service.bridgePort }}
      targetPort: bridge
      protocol: TCP
  selector:
    {{- include "moltbot-chart.selectorLabels" . | nindent 4 }}
